### ISSUE TITLE
[1.18.1] Wild Azalea Trees in the wild doesn't have the new Azalea Log Type.

### ISSUE THREAD

**Issue by Gbergz** [samedifferent/Azalea#3]
Title^

Any wild Azalea Tree doesn't contain the new wood type, is this a bug or on purpose?

Bone Mealing an Azalea Sapling gives you the new log type however.

**Minecraft**: 1.18.1
**Forge**: 39.0.19
**Better Azalea**: 3.0.0 | https://www.curseforge.com/minecraft/mc-mods/better-azalea/files/3548155

**Image:** 
![image](https://user-images.githubusercontent.com/26634554/149307547-54b98037-274f-4a41-ab7b-51c55f5b228d.png)

**-** Gbergz

**Comment by samedifferent** [comment]
This is because my mod does not modify the azalea trees that are generated by vanilla.

**Comment by Gbergz** [comment]
Gotcha. Thought that was the case. Wanted to double check.

Thanks
